### ISSUE TITLE
Add the missing logic to the Processing Lambda Skeleton Code

### ISSUE THREAD

**Issue by dbarrous** [HERMES-SOC/sdc_aws_processing_lambda#1]
**Description:**
Fill out the blanks and complete the logic for the Processing Lambda Function. 
Repo to function: https://github.com/HERMES-SOC/swsoc-processing-lambda

**Deliverable:**
Completed Processing Lambda Function

**Comment by ehsteve** [comment]
Is this the right place for this issue?
